site_name: Модуль Контур.Фокус для 1С
nav:
  - Домашняя: index.md
  
theme: 
  name: material
  language: ru
  logo: 'images/logo.png'
  favicon: 'images/icon.png'
  palette:
    primary: '#D9F1E3'
	accent: '#3C7252'