site_name: Модуль Контур.Фокус для 1С
nav:
  - О модуле: index.md
theme:
  name: material
  language: ru
  logo: assets/images/logo.png
  favicon: assets/images/icon.png
  palette:
    primary: Green
    accent: indigo
